# Generated by Django 4.2.26 on 2026-02-10 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='choice',
            field=models.CharField(choices=[('stork', 'Stork'), ('comfort', 'Comfort'), ('XL', 'XL'), ('Premium', 'Premium')], default='stork', max_length=20),
        ),
    ]
